version: "3.9"
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: synopsis
    depends_on:
      - database
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - /data:/data

  cache:
    container_name: cache
    image: redis
    ports:
      - "6379:6379"
    restart: always

  database:
    container_name: database
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - /data/database:/var/lib/postgresql/data

volumes:
  data: